name: Deployment
on:
    workflow_dispatch:
    workflow_run:
        workflows: ["image-build-push"]
        types:
            - completed

jobs:
    Deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            # - name: image tag
            #   uses: actions/download-artifact@v4
            #   with:
            #     name: image_tag
            #     path: .

            - name: list files
              run: |
                  ls -la

            - name: Read tag from file
              id: read
              run: |
                  IMAGE_TAG=$(cat image_tag.txt)
                  echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
            - name: Deploy to Docker Hub
              run: |
                  docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker-backend:${{ steps.read.outputs.image_tag }}
                  docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend:${{ steps.read.outputs.image_tag }}
                  docker images