name: image-build-push
on:
    # push:
    #     branches:
    #     - main
    #     paths:
    #         - frontend/**
    #         - .github/workflows/frontend.yml
    workflow_dispatch:

jobs:
    frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push frontend image
              env:
                IMAGE_NAME: expense-tracker-frontend
              uses: docker/build-push-action@v6
              with:
                  context: frontend/
                  file: frontend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    backend:
        runs-on: ubuntu-latest
        needs: [frontend]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push backend image
              env:
                IMAGE_NAME: expense-tracker-backend
              uses: docker/build-push-action@v6
              with:
                  context: backend/
                  file: backend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    image_tag:
      runs-on: ubuntu-latest
      needs: [frontend, backend]
      steps:
          - name: image tag
            run: echo "${{ github.run_number }}" > image_tag.txt
              
          - name: Upload image tag
            uses: actions/upload-artifact@v4
            with:
                name: image_tag
                path: image_tag.txt