name: image-build-push
on:
    push:
        branches:
        - main
        paths:
            - frontend/**
            - backend/**
            - .github/workflows/Image-build-push.yml
    workflow_dispatch:

jobs:
    frontend:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push frontend image
              env:
                IMAGE_NAME: expense-tracker-frontend
              uses: docker/build-push-action@v6
              with:
                  context: frontend/
                  file: frontend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    backend:
        runs-on: self-hosted
        needs: [frontend]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push backend image
              env:
                IMAGE_NAME: expense-tracker-backend
              uses: docker/build-push-action@v6
              with:
                  context: backend/
                  file: backend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    image_tag:
      runs-on: self-hosted
      needs: [frontend, backend]
      steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: image tag
            run: echo "${{ github.run_number }}" > image_tag.txt
              
          - name: Upload image tag
            run: |
              git config  user.name "github-actions"
              git config  user.email "githubactions@noreply.com"
              git add image_tag.txt
              git commit -m "Update image tag"
              git push origin main
